//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public string TypeActivity { get; set; }
        public string Location { get; set; }
        public int Id { get; set; }
        public Nullable<int> Fare { get; set; }
        public Nullable<int> NoOfPeople { get; set; }
        public string Duration { get; set; }
        public Nullable<int> Book { get; set; }
        public Nullable<int> SaveProduct { get; set; }
    }
}
