//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Air
    {
        public string Name { get; set; }
        public int Id { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public string ArrivalTime { get; set; }
        public string DepartureTime { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Book { get; set; }
        public Nullable<int> SaveProduct { get; set; }
    }
}
