//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public string Name { get; set; }
        public int Id { get; set; }
        public Nullable<int> Book { get; set; }
        public Nullable<int> SaveProduct { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string RegState { get; set; }
        public Nullable<int> Average { get; set; }
        public string FuelType { get; set; }
        public string GearType { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
