//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public string Name { get; set; }
        public int Id { get; set; }
        public string Location { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> WifiAvailaible { get; set; }
        public Nullable<int> NoOfRooms { get; set; }
        public Nullable<int> Book { get; set; }
        public Nullable<int> SaveProduct { get; set; }
    }
}
